spring:
  profiles:
    active: tidb # 초기 개발용 TiDB 클라우드 우선 적용. 추후 rds로 변경

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML

  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 30m

logging:
  level:
    com.recipekr: DEBUG
    org.springframework.security: DEBUG
